### ISSUE TITLE
SuperAdmin -> Actions: add is_default, is_deletable boolean fields in table

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#14]
Add an is_default column on the `actions` table and then when I create a contest the is_default actions will be associated.

If that action has is_deletable = 0 then the Admin cannot delete that action on any contest.

The result of this is that a SuperAdmin will be able to choose default actions for Contests which will be associated. Some won't be able to be removed from the contests.

**Comment by amirgee007** [comment]
is_deletable is ok.
if i create a contest and the contest belongs to any action so i make that action is deletable false.
so the superadmin cannot delete this because its connected with the contest.

but we can also do this via relation before deleting action we can check if the action is associated to any contest then give an error message otherwise if it does not belong to any a contest then remove.
rather than we create new column is_deletable and then confirm on every deletion.

also for the is_default logic need more detail.

first time if i create contest its value will be 0 to 1 means associated.

then? if i delete that contest then it needs to be an update or not.

**Comment by amirgee007** [comment]
done
