### ISSUE TITLE
Frontend -> Registered page -> List of actions

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#17]
In the registered page there's a list of actions:
http://prntscr.com/kgo2ul

Here you'll have to list all the actions for a contest and if there are entry_actions they will be ticked

Here are some guidelines:

1. An action can be performed `actions_contests.max_entry_actions` times
2. You'll have to calculate the sum of the points an Entry has. I see it in SQL like this
    ```
		SELECT
			sum(points)
		FROM
			actions_contests
		LEFT JOIN entry_actions ON action_contest_id = actions_contests.id
		WHERE
			entry_id = 1
    ```
3. You'll have to write a migration to transform the unique index action_contest_id+entry_id to a normal index because right now an Action can't be performed multiple times by an Entry

**Comment by amirgee007** [comment]
I am the guest user and open,
http://contestr1.dev/contest-1

And then give 1234554321 order id to join the contest.
So the two rows will be added in the database
1: entry_actions
2: entry_actions
Then will show this page.
 http://prntscr.com/kh2bp7


Facebook and amazon are the entry_actions from the database,
But I am showing only not have any function to connect or any other when it click on the button.


1.	An action can be performed actions_contests.max_entry_actions times.
for this when I need to check this one?
when will the guest user join the contest?
if yes then we have only contest and the User Order ID,
so what need to be check for the max_entry_actions?
because the relation is 1-M for the contests and ActionContests?
so which record need to check first?

Also where we need to use the sum of total points for the particular Entry?

**Comment by amirgee007** [comment]
guset user visit the site and join the contest after he will see a page showing all action contests?

so what he needs to do for marking this?

because there are two ticks one black and one is green so how it will convert to green?

**Comment by amirgee007** [comment]
Here you'll have to list all the actions for a contest and if there are entry_actions they will be ticked.
i am showing like this,
so the contest that has been joined it has multiple entryActions so i am checking if the contest has some more than one entry actions then it will be tick otherwise not tick and then show action name and after that need to show points of the contest,
we have not any relation here of action contest with entry so cannot show its points? how can i do that?
still confused. have thought 2-3 hours on it last night to finish.
but then again commit some changes please pull the changes and check whats going on and then please share your screen and discuss the changes/fixes for once then I will update the code.
so it's my bad. 

@foreach($contest->actionsContests as $actionsContest)

                    <div class="win-step {{count($actionsContest->entryActions) > 0 ? 'done' : '' }}">
                        <div>
                            <i class="fa fa-check"></i>
                            {{$actionsContest->action->name}}

                            <b>{{ $entry->points }} points</b>
                           
                        </div>
                    </div>
                    @endforeach

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
Let me check it out

**Comment by amirgee007** [comment]
https://1drv.ms/v/s!Aib4kHkus8JmmQpCCe0wd0vHqeHw

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
Hey Hamad,

I've seen your video and your logic seems fine.

Here's my feedback:
http://lucianvasile.com/contestr/hamad-feedback-2018-08-14_11-34-32.mp4

**Comment by amirgee007** [comment]
ok mate.

**Comment by amirgee007** [comment]
please check.... i have update som logic.
please feedback,

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
Hey, 

I've checked your logic and it seems fine for now.

I will close this task even if there are some loopholes...
